---
title: "R Notebook"
output: 
  html_notebook:
    toc: TRUE
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(skimr)
library(DataExplorer)
```

## Loading data

```{r}
df <- read.csv(file="https://raw.githubusercontent.com/alfanugraha/tsa-handson/master/churn-bigml-20.csv", header = T, sep = ",")
str(df)
```

```{r}
skim(df)
```


```{r}
plot_intro(df)
```

```{r}
plot_str(df, type = "r")
```

## Visualisasi

### Histogram

```{r}
histo <- hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi")
```

```{r}
# batas selang
histo$breaks
histo$counts
histo$mids
```

```{r}
hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi", breaks = 30)
```

```{r}
n <- length(df$Total.day.calls)
k1 <- sqrt(n)
histo2 <- hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi", breaks = k1)
histo2
```

### Formula by H.A. Sturges


```{r}
k2 <- log2(n) + 1
histo3 <- hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi", breaks = k2)
histo3
```

### Formula by Rice University

```{r}
k3 <- 2 * n ^ 1/3
histo4 <- hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi", breaks = k3)
histo4
```

```{r}
hist(df$Total.day.calls, freq = F,
     main = "Distribusi Total Panggilan", 
     xlab = "Total Panggilan", 
     ylab="Frekuensi",
     xlim=c(0, 150),
     ylim=c(0,0.02)
)

curve(
  dnorm(x,
        mean = mean(df$Total.day.calls), 
        sd = sd(df$Total.day.calls)
  ),
  add = T, lwd = 2
)
```

```{r}
par(mfrow=c(1, 2))

# total panggilan di bawah 100
hist(df[ df$Total.day.calls < 100, ]$Total.day.calls, 
     main = "Total panggilan", 
     xlab = "Jumlah panggilan di bawah 100", 
     ylab = "Frekuensi",
     col = "green")

# total panggilan di atas 100
hist(df[ df$Total.day.calls > 100, ]$Total.day.calls, 
     main = "Total panggilan", 
     xlab = "Jumlah panggilan di bawah 100", 
     ylab = "Frekuensi",
     col = "blue")
```

```{r}
plot(
  density(df$Total.day.calls), 
  main = "Perbandingan" 
)

lines(
  density(df$Total.eve.calls),
  col = "green"
)

lines(
  density(df$Total.night.calls), 
  col = "red"
)

legend(
  "topright",
  c("Day Calls", "Evening Calls", "Night Calls"),
  col = c("black", "green", "red"), lty = 1
)
```

```{r}
box1 <- boxplot(
  df$Total.day.calls,
  main = "Total panggilan",
  horizontal = T,
  frame = F, 
  col = "green"
)
box1
```

```{r}
# nilai minimum
min(df$Total.day.calls)

# statistik 5 serangkai
quantile(df$Total.day.calls)
```

## Deteksi Pencilan

```{r}
Q1 <- quantile(df$Total.day.calls)[2]
Q3 <- quantile(df$Total.day.calls)[4]


batas_atas <- Q3 + (3/2 * Q3-Q1)
cat("batas atas = ", batas_atas, "\n")

batas_bawah <- Q1 - (3/2 * Q3-Q1)
cat("batas bawah = ", batas_bawah)
```

## Histogram dan Boxplot

```{r}
par(mfrow=c(2, 1))
hist(df$Total.day.calls, main = "Total panggilan (hari)", xlab = "Jumlah panggilan", ylab="Frekuensi", breaks = k3)
boxplot(
  df$Total.day.calls,
  main = "Total panggilan",
  horizontal = T,
  frame = F, 
  col = "green"
)
```

```{r}
rataan <- mean(df$Total.day.calls)
med <- median(df$Total.day.calls)
modus <- function(x) {
  nilai_unique <- unique(x)
  nilai_unique[which.max(tabulate(match(x, nilai_unique)))]
}
mod <- modus(df$Total.day.calls)

cat("rataan =", rataan, "\n")
cat("median = ", med, "\n")
cat("modus = ", mod )
```


